### ISSUE TITLE
occassional advance test failure 

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#513]
```
  ======================================================================
10:05:21
  FAIL: test_overlapped_particledatas_have_identical_particles_1 (__main__.AdvanceTest)
10:05:21
  ----------------------------------------------------------------------
10:05:21
  Traceback (most recent call last):
10:05:21
    File "/usr/lib/python3.8/site-packages/ddt.py", line 145, in wrapper
10:05:21
      return func(self, *args, **kwargs)
10:05:21
    File "test_advance.py", line 420, in test_overlapped_particledatas_have_identical_particles
10:05:21
      self._test_overlapped_particledatas_have_identical_particles(dim, interp_order, refinement_boxes)
10:05:21
    File "test_advance.py", line 409, in _test_overlapped_particledatas_have_identical_particles
10:05:21
      self.assertTrue(np.allclose(part1.v[idx1,0], part2.v[idx2,0], atol=1e-12))
10:05:21
  AssertionError: False is not true
10:05:21
  
10:05:21
  ----------------------------------------------------------------------
10:05:21
  Ran 17 tests in 47.217s
10:05:21
  
10:05:21
  FAILED (failures=1)

```
```

 ======================================================================
09:08:44
  FAIL: test_overlapped_particledatas_have_identical_particles_2 (__main__.AdvanceTest)
09:08:44
  ----------------------------------------------------------------------
09:08:44
  Traceback (most recent call last):
09:08:44
    File "/usr/lib/python3.8/site-packages/ddt.py", line 145, in wrapper
09:08:44
      return func(self, *args, **kwargs)
09:08:44
    File "test_advance.py", line 420, in test_overlapped_particledatas_have_identical_particles
09:08:44
      self._test_overlapped_particledatas_have_identical_particles(dim, interp_order, refinement_boxes)
09:08:44
    File "test_advance.py", line 409, in _test_overlapped_particledatas_have_identical_particles
09:08:44
      self.assertTrue(np.allclose(part1.v[idx1,0], part2.v[idx2,0], atol=1e-12))
09:08:44
  AssertionError: False is not true
```

**Comment by nicolasaunai** [comment]
from discussion : 
The sorting assumes deltas are uniquely identifying particles.
The deltas of both arrays are equal but the velocities aren't.
This could come from two particles having delta too close.

**Comment by PhilipDeegan** [comment]
having particle deltas as doubles doesn't seem to help at all

**Comment by PhilipDeegan** [comment]
how bout ?
![image](https://user-images.githubusercontent.com/30491/114401463-3c629400-9ba3-11eb-80e6-a8914cfd56d2.png)

**Comment by PhilipDeegan** [comment]
removed duplicates and compared without order via https://github.com/PHAREHUB/PHARE/pull/529/commits/91ab6c4b8bacecf04f57502493c1056968ccde60
