### ISSUE TITLE
b init discrepancy

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#580]
cannot use 1e-16 for 1d, but can for 2d :\

```
30: ======================================================================
30: ERROR: test_B_is_as_provided_by_user_2_2 (__main__.InitializationTest)
30: ----------------------------------------------------------------------
30: Traceback (most recent call last):
30:   File "/home/philix/git/phare/master/build/tests/simulator/test_initialization.py", line 255, in _test_B_is_as_provided_by_user
30:     np.testing.assert_allclose(bz, bz_fn(xbz), atol=1e-16, rtol=0)
30:   File "/opt/py/py/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
30:     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
30:   File "/opt/py/py/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 842, in assert_array_compare
30:     raise AssertionError(msg)
30: AssertionError: 
30: Not equal to tolerance rtol=0, atol=1e-16
30: 
30: Mismatched elements: 1 / 20 (5%)
30: Max absolute difference: 1.11022302e-16
30: Max relative difference: 1.46003987e-15
30:  x: array([-0.097237, -0.098325, -0.099144, -0.099692, -0.099966, -0.099966,
30:        -0.099692, -0.099144, -0.098325, -0.097237, -0.095882, -0.094264,
30:        -0.092388, -0.090259, -0.087882, -0.085264, -0.082413, -0.079335,
30:        -0.076041, -0.072537])
30:  y: array([-0.097237, -0.098325, -0.099144, -0.099692, -0.099966, -0.099966,
30:        -0.099692, -0.099144, -0.098325, -0.097237, -0.095882, -0.094264,
30:        -0.092388, -0.090259, -0.087882, -0.085264, -0.082413, -0.079335,
30:        -0.076041, -0.072537])
30: 
30: During handling of the above exception, another exception occurred:
30: Patch: box( Box([90],[99])), id(p0#3), Box([90],[99]))
```

**Comment by nicolasaunai** [comment]
I don't know the reason but given the error is still around 1e-15 it's probably ok...

**Comment by nicolasaunai** [comment]
I say too many issues to worry about 1e-15 vs 1e-16, closing

**Comment by PhilipDeegan** [comment]
there's a comment on the test about it too
