### ISSUE TITLE
HDF5 unable to create dataset on ionBeam test

### ISSUE THREAD

**Issue by loic-darrieu** [PHAREHUB/PHARE#699]
ion Beam test with AMR  on Cholesky:

```

import pyphare.pharein as ph #lgtm [py/import-and-import-from]
from pyphare.pharein import Simulation
from pyphare.pharein import MaxwellianFluidModel
from pyphare.pharein import ElectromagDiagnostics, FluidDiagnostics, ParticleDiagnostics
from pyphare.pharein import ElectronModel
from pyphare.simulator.simulator import Simulator
from pyphare.pharein import global_vars as gv
from pyphare.pharesee.hierarchy import get_times_from_h5
from tests.diagnostic import all_timestamps
from pyphare.pharesee.run import Run
import os
from pyphare.pharein.global_vars import sim



import matplotlib.pyplot as plt
import matplotlib as mpl
from mpl_toolkits.axes_grid1 import make_axes_locatable
import numpy as np
from scipy.optimize import curve_fit
from scipy.signal import find_peaks
from pyphare.pharesee import plotting
from pathlib import Path
mpl.use('Agg')



def config():

    # most unstable mode at k=0.19, that is lambda = 33
    # hence the length of the box is 33, and the fourier mode will be 1

    Simulation(
        smallest_patch_size=20,
        largest_patch_size=60,
        final_time=100,
        time_step=0.001,
        boundary_types="periodic",
        cells=165,
        dl=0.2,
        hyper_resistivity = 0.01,
        refinement_boxes={"L0": {"B0": [( 50, ), (110, )]},
                          "L1": {"B0": [(140, ), (180, )]} },
        diag_options={"format": "phareh5",
                      "options": {"dir": "ion_ion_beam1d", "mode": "overwrite"}}
    )

    def densityMain(x):
        return 1.

    def densityBeam(x):
        return .01

    def bx(x):
        return 1.

    def by(x):
        return np.cos(2*np.pi*x/33)*0.1

    def bz(x):
        return np.sin(2*np.pi*x/33)*0.1

    def vB(x):
        return 5.

    def v0(x):
        return 0.

    def vth(x):
        return np.sqrt(0.1)


    vMain = {
        "vbulkx": v0, "vbulky": v0, "vbulkz": v0,
        "vthx": vth, "vthy": vth, "vthz": vth,"nbr_part_per_cell":3000
    }


    vBulk = {
        "vbulkx": vB, "vbulky": v0, "vbulkz": v0,
        "vthx": vth, "vthy": vth, "vthz": vth
    }


    MaxwellianFluidModel(
        bx=bx, by=by, bz=bz,
        main={"charge": 1, "density": densityMain, **vMain},
        beam={"charge": 1, "density": densityBeam, **vBulk}
    )

    ElectronModel(closure="isothermal", Te=0.0)

    sim = ph.global_vars.sim

    timestamps = np.arange(0, sim.final_time, 0.1)

    for quantity in ["B","E"]:
        ElectromagDiagnostics(
            quantity=quantity,
            write_timestamps=timestamps,
            compute_timestamps=timestamps,
        )
    ParticleDiagnostics(quantity = "domain", population_name = "main" , write_timestamps=timestamps, compute_timestamps=timestamps)
    ParticleDiagnostics(quantity = "domain", population_name = "beam" , write_timestamps=timestamps, compute_timestamps=timestamps)





def yaebx(x, a, b):
    return a*np.exp(np.multiply(b, x))


def growth_b_right_hand(run_path,d):

    file = os.path.join(run_path, "EM_B.h5")
    times = get_times_from_h5(file)
    dt = times[1]-times[0]
    r = Run(run_path)
    first_mode = np.array([])
    

    for time in times:
        B_hier = r.GetB(time, merged=True, interp="linear")

        by_interpolator, xyz_finest = B_hier["By"]
        bz_interpolator, xyz_finest = B_hier["Bz"]

        # remove the last point so that "x" is periodic wo. last point = first point
        x = xyz_finest[0][:-1]

        by = by_interpolator(x)
        bz = bz_interpolator(x)

        # get the mode 1, as it is the most unstable in a box of length 33
        mode1 = np.absolute(np.fft.fft(by-1j*bz)[1])
        first_mode = np.append(first_mode, mode1)
    
    imax = find_peaks(first_mode,width = int(d/dt))[0][0]
    

    popt, pcov = curve_fit(yaebx, times[:imax-int(d/dt)], first_mode[:imax-int(d/dt)], p0=[0.08, 0.09])

    # now the signal is stripped from its exponential part
    damped_mode=first_mode[:imax-int(d/dt)]*yaebx(times[:imax-int(d/dt)], 1/popt[0], -popt[1])

    # find the omega for which "damped_mode" is the largest :
    # this term is twice the one it should be because "mode1" resulting from
    # an absolute value, this (cosx)^2 = cos(2x) then appears at the 2nd
    # harmonoic (hence the factor 0.5 to get "omega")
    # the factor "+1" is because we remove the DC component, so the value
    # given by argmax has also to miss this value
    omegas = np.fabs(np.fft.fft(damped_mode).real)
    omega = 0.5*(omegas[1:omegas.size//2].argmax()+1)*2*np.pi/times[imax-1 -int(d/dt)]


    return times, first_mode, popt[0], popt[1], damped_mode, omega


def main():

    from pybindlibs.cpp import mpi_rank

    config()
    simulator = Simulator(gv.sim)
    simulator.initialize()
    d= 10
    
    simulator.run()
    
    if mpi_rank() == 0:
    
        Path("phase_space").mkdir(parents=True, exist_ok=True)
        Path("mov_phase_space").mkdir(parents=True, exist_ok=True)
    
        times, first_mode, ampl, gamma, damped_mode, omega \
                = growth_b_right_hand(os.path.join(os.curdir, "ion_ion_beam1d"),d)

        dt = times[1]-times[0]
        imax = find_peaks(first_mode,width = int(d/dt))[0][0]
        fig, (ax1, ax2) = plt.subplots(2, 1,figsize=(10,5))

        ax1.set_title("Right Hand Resonant mode (Beam instability)")
        ax1.plot(times, first_mode, color = 'k',marker='o')
        ax1.plot(times[:imax], yaebx(times[:imax], ampl, gamma), color='r', linestyle='-', marker='')
        ax1.text(0.01, 0.80, "From Gary et al., 1985 (ApJ : 10.1086/162797)  ", transform=ax1.transAxes)
        ax1.set_ylabel("Most unstable mode")
        ax1.set_title("Right Hand Resonant mode (Beam instability)")
        ax1.text(0.01, 0.65, "gamma = {:5.3f}... expected 0.09".format(gamma), transform=ax1.transAxes)
        ax2.plot(times[:imax-int(d/dt)], damped_mode, color='g', linestyle='', marker='o')
        ax2.set_xlabel("Time")
        ax2.set_ylabel("Real mode")
        ax2.text(0.48, 0.30, "~ 3 periods until t=50", transform=ax2.transAxes)
        ax2.text(0.40, 0.20, "omega (real) = {:5.3f}... expected 0.19".format(omega), transform=ax2.transAxes)
        fig.savefig("ion_ion_beam1d.png")
        r = Run(os.path.join(os.curdir, "ion_ion_beam1d"))
        dt = times[1]-times[0]
        plt.close(fig)
        
        for t in times:
            ions = r.GetParticles(t, ["main","beam"])
            fig, ax = plt.subplots(figsize=(7,7),constrained_layout=True)
            
            ions.dist_plot(axis=("x", "Vx"), 
               ax = ax,           
               norm = 0.4,     
               finest=True,  
               gaussian_filter_sigma = (1,1) ,
               vmin=-2,vmax=7,
               dv=0.05,
               title="Phase space at = {:.4f}".format(t), 
               xlabel="x",
               ylabel= "vx" 
              )
            ax2 = ax.twinx() 
            
            B_hier = r.GetB(time = t, merged = True, interp = "linear")
            by_interpolator, xyz_finest = B_hier["By"]
            ax2.plot(xyz_finest[0],by_interpolator(xyz_finest[0]),linewidth = 2, color = 'k')
            ax.set_xlabel("x")
            ax.set_ylabel("Vx")
            ax2.set_ylabel("By")
            ax2.set_ylim((-0.2,0.2))
            fig.savefig("phase_space/t={:2.2f}.png".format(t)) 	
            fig.savefig("mov_phase_space/{:04d}.png".format(int(t/dt)))
            plt.close(fig)
            # compare with the values given gary et al. 1985
            #assert np.fabs(gamma-0.09) < 2e-2
            

if __name__=="__main__":
    main()

```
Error : 
```
[node027:194759] mca_base_component_repository_open: unable to open mca_op_avx: /mnt/beegfs/softs/opt/gcc_10.2.0/openmpi/4.1.0/lib/openmpi/mca_op_avx.so: undefined symbol: ompi_op_base_module_t_class (ignored)
[node027:194761] mca_base_component_repository_open: unable to open mca_op_avx: /mnt/beegfs/softs/opt/gcc_10.2.0/openmpi/4.1.0/lib/openmpi/mca_op_avx.so: undefined symbol: ompi_op_base_module_t_class (ignored)
[node027:194760] mca_base_component_repository_open: unable to open mca_op_avx: /mnt/beegfs/softs/opt/gcc_10.2.0/openmpi/4.1.0/lib/openmpi/mca_op_avx.so: undefined symbol: ompi_op_base_module_t_class (ignored)
[node027:194758] mca_base_component_repository_open: unable to open mca_op_avx: /mnt/beegfs/softs/opt/gcc_10.2.0/openmpi/4.1.0/lib/openmpi/mca_op_avx.so: undefined symbol: ompi_op_base_module_t_class (ignored)
[node027:194762] mca_base_component_repository_open: unable to open mca_op_avx: /mnt/beegfs/softs/opt/gcc_10.2.0/openmpi/4.1.0/lib/openmpi/mca_op_avx.so: undefined symbol: ompi_op_base_module_t_class (ignored)
At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.

At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.

At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.

At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.

At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.
At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.

At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.

At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.

At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.


At :/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/subprojects/samrai/source/SAMRAI/hier/PatchHierarchy.cpp line :325 message: PHARE_hierarchy:  Using zero `proper_nesting_buffer' values.

t =  0.00100  -  0.75922sec  - total  0.7592sec
t =  0.00200  -  0.69951sec  - total   1.459sec
(...)
t =  1.19800  -  0.69499sec  - total   833.6sec
t =  1.19900  -  0.68762sec  - total   834.3sec
HDF5-DIAG: Error detected in HDF5 (1.12.1) MPI-process 4:
  #000: H5D.c line 141 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to create file
  #001: H5VLcallback.c line 1806 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 1771 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_dataset.c line 73 in H5VL__native_dataset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #004: H5Dint.c line 396 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #005: H5L.c line 1767 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #006: H5L.c line 2009 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #007: H5Gtraverse.c line 837 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.12.1) MPI-process 2:
  #000: H5D.c line 141 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to create file
  #001: H5VLcallback.c line 1806 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 1771 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_dataset.c line 73 in H5VL__native_dataset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #004: H5Dint.c line 396 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #005: H5L.c line 1767 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #006: H5L.c line 2009 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #007: H5Gtraverse.c line 837 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #008: H5Gtraverse.c line 613 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #009: H5L.c line 1802 in H5L__link_cb(): name already exists
    major: Links
HDF5-DIAG: Error detected in HDF5 (1.12.1) HDF5-DIAG: Error detected in HDF5 (1.12.1) MPI-process 3:
  #000: H5D.c line 141 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to create file
  #001: H5VLcallback.c line 1806 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 1771 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_dataset.c line 73 in H5VL__native_dataset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #004: H5Dint.c line 396 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #005: H5L.c line 1767 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #006: H5L.c line 2009 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #007: H5Gtraverse.c line 837 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #008: H5Gtraverse.c line 613 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #009: H5L.c line 1802 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
HDF5-DIAG: Error detected in HDF5 (1.12.1) MPI-process 1:
  #000: H5D.c line 141 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to create file
  #001: H5VLcallback.c line 1806 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 1771 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_dataset.c line 73 in H5VL__native_dataset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #004: H5Dint.c line 396 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #005: H5L.c line 1767 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #006: H5L.c line 2009 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #007: H5Gtraverse.c line 837 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #008: H5Gtraverse.c line 613 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #009: H5L.c line 1802 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
  #008: H5Gtraverse.c line 613 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #009: H5L.c line 1802 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
    minor: Object already exists
MPI-process 0:
  #000: H5D.c line 141 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to create file
  #001: H5VLcallback.c line 1806 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 1771 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_dataset.c line 73 in H5VL__native_dataset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #004: H5Dint.c line 396 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #005: H5L.c line 1767 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #006: H5L.c line 2009 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #007: H5Gtraverse.c line 837 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #008: H5Gtraverse.c line 613 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #009: H5L.c line 1802 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
Traceback (most recent call last):
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 243, in <module>
Traceback (most recent call last):
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 243, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 243, in <module>
Traceback (most recent call last):
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 243, in <module>
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 243, in <module>
    main()
    main()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 173, in main
    main()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 173, in main
    main()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 173, in main
    main()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 173, in main
  File "/mnt/beegfs/workdir/loic.darrieumerlou/runs/run019/run2/8/ion_ion_beam1d.py", line 173, in main
    simulator.run()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 118, in run
    simulator.run()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 118, in run
    simulator.run()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 118, in run
    simulator.run()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 118, in run
    simulator.run()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 118, in run
    self.advance()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 100, in advance
    self.advance()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 100, in advance
    self.advance()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 100, in advance
    self.advance()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 100, in advance
    self.advance()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 100, in advance
    if self._auto_dump() and self.post_advance != None:
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 134, in _auto_dump
    if self._auto_dump() and self.post_advance != None:
    if self._auto_dump() and self.post_advance != None:
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 134, in _auto_dump
    if self._auto_dump() and self.post_advance != None:
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 134, in _auto_dump
    if self._auto_dump() and self.post_advance != None:
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 134, in _auto_dump
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 134, in _auto_dump
    return self.auto_dump and self.dump()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 141, in dump
    return self.auto_dump and self.dump()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 141, in dump
    return self.auto_dump and self.dump()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 141, in dump
    return self.auto_dump and self.dump()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 141, in dump
    return self.auto_dump and self.dump()
  File "/mnt/beegfs/workdir/loic.darrieumerlou/PHARE/pyphare/pyphare/simulator/simulator.py", line 141, in dump
    return self.cpp_sim.dump(timestamp=self.currentTime(), timestep=self.timeStep())
RuntimeError: Unable to create the dataset "/t/1.2000000000/pl0/p0#0/EM_B_z": (Links) Object already exists
    return self.cpp_sim.dump(timestamp=self.currentTime(), timestep=self.timeStep())
RuntimeError: Unable to create the dataset "/t/1.2000000000/pl0/p0#0/EM_B_z": (Links) Object already exists
    return self.cpp_sim.dump(timestamp=self.currentTime(), timestep=self.timeStep())
RuntimeError: Unable to create the dataset "/t/1.2000000000/pl0/p0#0/EM_B_z": (Links) Object already exists
    return self.cpp_sim.dump(timestamp=self.currentTime(), timestep=self.timeStep())
RuntimeError: Unable to create the dataset "/t/1.2000000000/pl0/p0#0/EM_B_z": (Links) Object already exists
    return self.cpp_sim.dump(timestamp=self.currentTime(), timestep=self.timeStep())
RuntimeError: Unable to create the dataset "/t/1.2000000000/pl0/p0#0/EM_B_z": (Links) Object already exists
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[38782,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

During this run, I copied two times the cholesky log file from to kaa so it could have interfered.
I tried to rerun this test without copying during the run and it worked normally this time

**Comment by nicolasaunai** [comment]
I got this kind of hdf5 error as well, but can not reproduce it consistently. It seemed correlated with using too many MPI processes for a small domain... maybe some proc has no patch or something. Would need to investigate, but put it as low priority for now since have not seen the error for a while.

**Comment by nicolasaunai** [comment]
have not seen h5 errors in a while, closing.
