### ISSUE TITLE
interpolator_test - DeprecationWarning:     `bspline` is deprecated!

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#771]
```
/github/workspace/tests/core/numerics/interpolator/interpolator_test.py:65: DeprecationWarning:     `bspline` is deprecated!
    `scipy.signal.bspline` is deprecated in SciPy 1.11 and will be
    removed in SciPy 1.13.
    The exact equivalent (for a float array `x`) is
    >>> from scipy.interpolate import BSpline
    >>> knots = np.arange(-(n+1)/2, (n+3)/2)
    >>> out = BSpline.basis_element(knots)(x)
    >>> out[(x < knots[0]) | (x > knots[-1])] = 0.0
  splines_val[:,ipos] = bspline(node_splines[:, ipos] - pos, order)
```

**Comment by PhilipDeegan** [comment]
This now seems to be blocking the macos build on github actions

```
Traceback (most recent call last):
  File "/Users/runner/work/PHARE/PHARE/tests/core/numerics/interpolator/interpolator_test.py", line 85, in <module>
    main()
  File "/Users/runner/work/PHARE/PHARE/tests/core/numerics/interpolator/interpolator_test.py", line 38, in main
    from scipy.signal import bspline
ImportError: cannot import name 'bspline' from 'scipy.signal' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/signal/__init__.py)
make[2]: *** [tests/core/numerics/interpolator/test-interpolator] Error 1
make[1]: *** [tests/core/numerics/interpolator/CMakeFiles/test-interpolator.dir/all] Error 2
```

**Comment by PhilipDeegan** [comment]
the new version supposedly looks something like this 

```
        The exact equivalent (for a float array `x`) is::

            >>> import numpy as np
            >>> from scipy.interpolate import BSpline
            >>> knots = np.arange(-(n+1)/2, (n+3)/2)
            >>> out = BSpline.basis_element(knots)(x)
            >>> out[(x < knots[0]) | (x > knots[-1])] = 0.0
```

for an array `x`, but I don't really know how to change what we have to match this
