### ISSUE TITLE
test_refine_field shape mismatch

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#853]
when running `tests/simulator/refinement/test_2d_10_core.py` with `mpirun -n 10`

```
  File "/path/to/git/phare/master/tests/simulator/refinement/test_2d_10_core.py", line 206, in <module>
    main()
  File "/path/to/git/phare/master/tests/simulator/refinement/test_2d_10_core.py", line 202, in main
    Simulator(sim, post_advance=post_advance).run()
  File "/path/to/git/phare/master/pyphare/pyphare/simulator/simulator.py", line 164, in run
    self.advance()
  File "/path/to/git/phare/master/pyphare/pyphare/simulator/simulator.py", line 142, in advance
    self.post_advance(self.cpp_sim.currentTime())
  File "/path/to/git/phare/master/tests/simulator/refinement/test_2d_10_core.py", line 179, in post_advance
    test.base_test_field_level_ghosts_via_subcycles_and_coarser_interpolation(
  File "/path/to/git/phare/master/tests/simulator/test_advance.py", line 582, in base_test_field_level_ghosts_via_subcycles_and_coarser_interpolation
    interpolated_fields = refine_time_interpolate(
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/git/phare/master/tests/amr/data/field/refine/test_refine_field.py", line 399, in refine_time_interpolate
    refine_algo(
  File "/path/to/git/phare/master/tests/amr/data/field/refine/test_refine_field.py", line 98, in refine_electric
    fine_data[1::2, ::2] = coarse_data[:, :]
```

**Comment by nicolasaunai** [comment]
Note: that test is not run currently on nightly builds as it is MPI and we run only serial tests.
To investigate...

**Comment by PhilipDeegan** [comment]
having tried the nightly build with mpi tests, we are seeing this again

```
20:43:29   Traceback (most recent call last):
20:43:29     File "/opt/buildagent/work/3bd323ee5a73a841/build/tests/simulator/refinement/test_2d_10_core.py", line 198, in <module>
20:43:29       main()
20:43:29     File "/opt/buildagent/work/3bd323ee5a73a841/build/tests/simulator/refinement/test_2d_10_core.py", line 194, in main
20:43:29       Simulator(sim, post_advance=post_advance).run()
20:43:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/simulator/simulator.py", line 185, in run
20:43:29       self.advance()
20:43:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/simulator/simulator.py", line 163, in advance
20:43:29       self.post_advance(self.cpp_sim.currentTime())
20:43:29     File "/opt/buildagent/work/3bd323ee5a73a841/build/tests/simulator/refinement/test_2d_10_core.py", line 171, in post_advance
20:43:29       test.base_test_field_level_ghosts_via_subcycles_and_coarser_interpolation(
20:43:29     File "/opt/buildagent/work/3bd323ee5a73a841/build/tests/simulator/test_advance.py", line 577, in base_test_field_level_ghosts_via_subcycles_and_coarser_interpolation
20:43:29       interpolated_fields = refine_time_interpolate(
20:43:29                             ^^^^^^^^^^^^^^^^^^^^^^^^
20:43:29     File "/opt/buildagent/work/3bd323ee5a73a841/build/tests/amr/data/field/refine/test_refine_field.py", line 399, in refine_time_interpolate
20:43:29       refine_algo(
20:43:29     File "/opt/buildagent/work/3bd323ee5a73a841/build/tests/amr/data/field/refine/test_refine_field.py", line 98, in refine_electric
20:43:29       fine_data[1::2, ::2] = coarse_data[:, :]
20:43:29       ~~~~~~~~~^^^^^^^^^^^
20:43:29   ValueError: could not broadcast input array from shape (18,24) into shape (17,24)
```
