### ISSUE TITLE
td1dtagged - sporadic test failure

### ISSUE THREAD

**Issue by PhilipDeegan** [PHAREHUB/PHARE#877]
https://github.com/PHAREHUB/PHARE/blob/5933e40de0f5de95cb12aaca0758eadd1ccf3924/tests/functional/tdtagged/td1dtagged.py#L152

if it was line 151 I would understand, but this seems odd.
I've seen it at least once before, but is not always happening.

```
16:11:29   Traceback (most recent call last):
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/build/tests/functional/tdtagged/td1dtagged.py", line 282, in <module>
16:11:29       main()
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/build/tests/functional/tdtagged/td1dtagged.py", line 278, in main
16:11:29       make_figure()
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/build/tests/functional/tdtagged/td1dtagged.py", line 152, in make_figure
16:11:29       BwT = rwT.GetB(plot_time, merged=True, interp="linear")
16:11:29             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/pharesee/run/run.py", line 99, in GetB
16:11:29       return self._get(hier, time, merged, interp)
16:11:29              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/pharesee/run/run.py", line 73, in _get
16:11:29       dl = self.GetDl(time=time)
16:11:29            ^^^^^^^^^^^^^^^^^^^^^
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/pharesee/run/run.py", line 262, in GetDl
16:11:29       hier = self._get_hierarchy(time, h5_filename.split("/")[-1])
16:11:29              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/pharesee/run/run.py", line 62, in _get_hierarchy
16:11:29       return _get_hier(hier)
16:11:29              ^^^^^^^^^^^^^^^
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/pharesee/run/run.py", line 55, in _get_hier
16:11:29       return hierarchy_from(
16:11:29              ^^^^^^^^^^^^^^^
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/pharesee/hierarchy/__init__.py", line 37, in hierarchy_from
16:11:29       return hierarchy_fromh5(h5_filename, times, hier, **kwargs)
16:11:29              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/pharesee/hierarchy/fromh5.py", line 303, in hierarchy_fromh5
16:11:29       return new_from_h5(h5_filename, time, **kwargs)
16:11:29              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/pharesee/hierarchy/fromh5.py", line 274, in new_from_h5
16:11:29       patch_levels = patch_levels_from_h5(h5f, time, selection_box=selection_box[it])
16:11:29                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:11:29     File "/opt/buildagent/work/3bd323ee5a73a841/pyphare/pyphare/pharesee/hierarchy/fromh5.py", line 170, in patch_levels_from_h5
16:11:29       for lvl_key, lvl in h5f[h5_time_grp_key][time].items():

16:11:29     File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
16:11:29     File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
16:11:29     File "/usr/lib64/python3.12/site-packages/h5py/_hl/group.py", line 357, in __getitem__
16:11:29       oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
16:11:29             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:11:29     File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
16:11:29     File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
16:11:29     File "h5py/h5o.pyx", line 189, in h5py.h5o.open
16:11:29   KeyError: "Unable to open object (object '11.0000000000' doesn't exist)"
```

**Comment by PhilipDeegan** [comment]
https://hephaistos.lpp.polytechnique.fr/teamcity/buildConfiguration/Phare_Phare_GhMasterGccSamraisubCaliperFunctional/83298?buildTab=log&logView=flowAware&linesState=1269&focusLine=1532

**Comment by PhilipDeegan** [comment]
todo, close if we don't see the tdtagged issue hereafter

**Comment by nicolasaunai** [comment]
check if h5 file has time like 11.000000...1 or something and so the time/key asked may not be found in the file.

**Comment by PhilipDeegan** [comment]
this was fixed by taking checking all hdf5 files for the requested time https://github.com/PHAREHUB/PHARE/blob/master/pyphare/pyphare/pharesee/run/run.py#L255

new issue for longer term fix incoming
